// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdzOoV2IecbtL7AxZwQ4oKKcY4dEcGkCk',
    appId: '1:585297582296:web:58456246fabced587d9fad',
    messagingSenderId: '585297582296',
    projectId: 'chat-me-60f86',
    authDomain: 'chat-me-60f86.firebaseapp.com',
    storageBucket: 'chat-me-60f86.appspot.com',
    measurementId: 'G-JH6VQDX6FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkRaM8Z1ibhA6olu2Gk-1W8vfbQQZE4A',
    appId: '1:585297582296:android:d00f2c503c34ce1a7d9fad',
    messagingSenderId: '585297582296',
    projectId: 'chat-me-60f86',
    storageBucket: 'chat-me-60f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9hJC5E_RXq4YHdn2bDw5eIXGkAOISN_Y',
    appId: '1:585297582296:ios:3ed12285467ecae17d9fad',
    messagingSenderId: '585297582296',
    projectId: 'chat-me-60f86',
    storageBucket: 'chat-me-60f86.appspot.com',
    androidClientId: '585297582296-prqj6t0t7nfnneagstu4a40c3uvklbqq.apps.googleusercontent.com',
    iosClientId: '585297582296-gcr04p3qmjvaul5a0sovbhb7eqfm385o.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
